// Using Ionicons, Feather, and MaterialCommunityIcons
export const defaultCategories = {
  'airtravel-airplane-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Air Travel',
    categoryId: 'airtravel-airplane-materialcommunityicons',
    iconName: 'airplane',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'alcohol-glass-cocktail-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Alcohol',
    categoryId: 'alcohol-glass-cocktail-materialcommunityicons',
    iconName: 'glass-cocktail',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'autoinsurance-car-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Auto Insurance',
    categoryId: 'autoinsurance-car-materialcommunityicons',
    iconName: 'car',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'autopayment-car-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Auto Payment',
    categoryId: 'autopayment-car-materialcommunityicons',
    iconName: 'car',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'babysupplies-baby-buggy-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Baby Supplies',
    categoryId: 'babysupplies-baby-buggy-materialcommunityicons',
    iconName: 'baby-buggy',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'babysitterdaycare-baby-buggy-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Babysitter & Daycare',
    categoryId: 'babysitterdaycare-baby-buggy-materialcommunityicons',
    iconName: 'baby-buggy',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'books-book-open-variant-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Books',
    categoryId: 'books-book-open-variant-materialcommunityicons',
    iconName: 'book-open-variant',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'clothing-watch-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Clothing',
    categoryId: 'clothing-watch-materialcommunityicons',
    iconName: 'watch',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'gifts-charity-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Charity',
    categoryId: 'gifts-charity-materialcommunityicons',
    iconName: 'charity',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'childsupport-baby-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Child Support',
    categoryId: 'childsupport-baby-materialcommunityicons',
    iconName: 'baby',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'coffeeshops-coffee-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Coffee Shops',
    categoryId: 'coffeeshops-coffee-materialcommunityicons',
    iconName: 'coffee',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'dentist-md-medkit-ionicons': {
    isStandardCategory: true,
    categoryName: 'Dentist',
    categoryId: 'dentist-md-medkit-ionicons',
    iconName: 'md-medkit',
    iconLibrary: 'Ionicons',
  },
  'doctor-md-medkit-ionicons': {
    isStandardCategory: true,
    categoryName: 'Doctor',
    categoryId: 'doctor-md-medkit-ionicons',
    iconName: 'md-medkit',
    iconLibrary: 'Ionicons',
  },
  'electronics-cellphone-link-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Electronics',
    categoryId: 'electronics-cellphone-link-materialcommunityicons',
    iconName: 'cellphone-link',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'events-star-feather': {
    isStandardCategory: true,
    categoryName: 'Events',
    categoryId: 'events-star-feather',
    iconName: 'star',
    iconLibrary: 'Feather',
  },
  'eyecare-eye-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Eye Care',
    categoryId: 'eyecare-eye-materialcommunityicons',
    iconName: 'eye',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'fastfood-pizza-ionicons': {
    isStandardCategory: true,
    categoryName: 'Fast Food',
    categoryId: 'fastfood-pizza-ionicons',
    iconName: 'md-pizza',
    iconLibrary: 'Ionicons',
  },
  'atmfee-atm-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Fees - ATM',
    categoryId: 'atmfee-atm-materialcommunityicons',
    iconName: 'atm',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'bankfee-bank-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Fees - Bank',
    categoryId: 'bankfee-bank-materialcommunityicons',
    iconName: 'bank',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'latefee-messagealert-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Fees - Late',
    categoryId: 'latefee-messagealert-materialcommunityicons',
    iconName: 'message-alert',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'servicefee-message-alert-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Fees - Service',
    categoryId: 'servicefee-message-alert-materialcommunityicons',
    iconName: 'message-alert',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'gasfuel-gas-station-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Gas & Fuel',
    categoryId: 'gasfuel-gas-station-materialcommunityicons',
    iconName: 'gas-station',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'gifts-md-gift-ionicons': {
    isStandardCategory: true,
    categoryName: 'Gifts',
    categoryId: 'gifts-md-gift-ionicons',
    iconName: 'md-gift',
    iconLibrary: 'Ionicons',
  },
  'groceries-cart-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Groceries',
    categoryId: 'groceries-cart-materialcommunityicons',
    iconName: 'cart',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'gym-dumbbell-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Gym',
    categoryId: 'gym-dumbbell-materialcommunityicons',
    iconName: 'dumbbell',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'hair-md-cut-ionicons': {
    isStandardCategory: true,
    categoryName: 'Hair',
    categoryId: 'hair-md-cut-ionicons',
    iconName: 'md-cut',
    iconLibrary: 'Ionicons',
  },
  'healthinsurance-md-medkit-ionicons': {
    isStandardCategory: true,
    categoryName: 'Health Insurance',
    categoryId: 'healthinsurance-md-medkit-ionicons',
    iconName: 'md-medkit',
    iconLibrary: 'Ionicons',
  },
  'hobbies-md-happy-ionicons': {
    isStandardCategory: true,
    categoryName: 'Hobbies',
    categoryId: 'hobbies-md-happy-ionicons',
    iconName: 'md-happy',
    iconLibrary: 'Ionicons',
  },
  'homephone-phone-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Home Phone',
    categoryId: 'homephone-phone-materialcommunityicons',
    iconName: 'phone',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'homerepairs-home-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Home Repairs',
    categoryId: 'homerepairs-home-materialcommunityicons',
    iconName: 'home',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'hotel-hotel-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Hotel',
    categoryId: 'hotel-hotel-materialcommunityicons',
    iconName: 'hotel',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'internet-md-globe-ionicons': {
    isStandardCategory: true,
    categoryName: 'Internet',
    categoryId: 'internet-md-globe-ionicons',
    iconName: 'md-globe',
    iconLibrary: 'Ionicons',
  },
  'investment-currency-usd-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Investments',
    categoryId: 'investment-currency-usd-materialcommunityicons',
    iconName: 'currency-usd',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'laundry-washing-machine-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Laundry',
    categoryId: 'laundry-washing-machine-materialcommunityicons',
    iconName: 'washing-machine',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'legal-md-paper-ionicons': {
    isStandardCategory: true,
    categoryName: 'Legal',
    categoryId: 'legal-md-paper-ionicons',
    iconName: 'md-paper',
    iconLibrary: 'Ionicons',
  },
  'mobilephone-cellphone-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Mobile Phone',
    categoryId: 'mobilephone-cellphone-materialcommunityicons',
    iconName: 'cellphone',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'movies-filmstrip-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Movies',
    categoryId: 'movies-filmstrip-materialcommunityicons',
    iconName: 'filmstrip',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'music-headphones-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Music',
    categoryId: 'music-headphones-materialcommunityicons',
    iconName: 'headphones',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'newspapermagazines-newspaper-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Newspaper & Magazines',
    categoryId: 'newspapermagazines-newspaper-materialcommunityicons',
    iconName: 'newspaper',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'officesupplies-paperclip-feather': {
    isStandardCategory: true,
    categoryName: 'Office Supplies',
    categoryId: 'officesupplies-paperclip-feather',
    iconName: 'paperclip',
    iconLibrary: 'Feather',
  },
  'other-help-circle-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Other',
    categoryId: 'other-help-circle-materialcommunityicons',
    iconName: 'help-circle',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'parking-parking-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Parking',
    categoryId: 'parking-parking-materialcommunityicons',
    iconName: 'parking',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'pharmacy-pharmacy-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Pharmacy',
    categoryId: 'pharmacy-pharmacy-materialcommunityicons',
    iconName: 'pharmacy',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'printing-printer-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Printing',
    categoryId: 'printing-printer-materialcommunityicons',
    iconName: 'printer',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'publictransportation-bus-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Public Transportation',
    categoryId: 'publictransportation-bus-materialcommunityicons',
    iconName: 'bus',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'rent-home-city-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Rent',
    categoryId: 'rent-home-city-materialcommunityicons',
    iconName: 'home-city',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'rentalcar-car-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Rental Car',
    categoryId: 'rentalcar-car-materialcommunityicons',
    iconName: 'car',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'restaurants-silverware-fork-knife-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Restaurants',
    categoryId: 'restaurants-silverware-fork-knife-materialcommunityicons',
    iconName: 'silverware-fork-knife',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'taxisrideshares-taxi-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Rideshares & Taxis',
    categoryId: 'taxisrideshares-taxi-materialcommunityicons',
    iconName: 'taxi',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'serviceautoparts-towing-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Service & Auto Parts',
    categoryId: 'serviceautoparts-towing-materialcommunityicons',
    iconName: 'towing',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'schoolsupplies-school-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'School Supplies',
    categoryId: 'schoolsupplies-school-materialcommunityicons',
    iconName: 'school',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'shipping-truck-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Shipping',
    categoryId: 'shipping-truck-materialcommunityicons',
    iconName: 'truck',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'software-logo-windows-ionicons': {
    isStandardCategory: true,
    categoryName: 'Software',
    categoryId: 'software-logo-windows-ionicons',
    iconName: 'logo-windows',
    iconLibrary: 'Ionicons',
  },
  'spamassage-spa-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Spa & Massage',
    categoryId: 'spamassage-spa-materialcommunityicons',
    iconName: 'spa',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'sportinggoods-basketball-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Sporting Goods',
    categoryId: 'sportinggoods-basketball-materialcommunityicons',
    iconName: 'basketball',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'sports-football-ionicons': {
    isStandardCategory: true,
    categoryName: 'Sports',
    categoryId: 'sports-football-ionicons',
    iconName: 'md-football',
    iconLibrary: 'Ionicons',
  },
  'studentloan-school-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Student Loan',
    categoryId: 'studentloan-school-materialcommunityicons',
    iconName: 'school',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'taxesfederal-md-paper-ionicons': {
    isStandardCategory: true,
    categoryName: 'Taxes - Federal',
    categoryId: 'taxesfederal-md-paper-ionicons',
    iconName: 'md-paper',
    iconLibrary: 'Ionicons',
  },
  'taxesstate-md-paper-ionicons': {
    isStandardCategory: true,
    categoryName: 'Taxes - State',
    categoryId: 'taxesstate-md-paper-ionicons',
    iconName: 'md-paper',
    iconLibrary: 'Ionicons',
  },
  'taxeslocal-md-paper-ionicons': {
    isStandardCategory: true,
    categoryName: 'Taxes - Local',
    categoryId: 'taxeslocal-md-paper-ionicons',
    iconName: 'md-paper',
    iconLibrary: 'Ionicons',
  },
  'taxessales-md-paper-ionicons': {
    isStandardCategory: true,
    categoryName: 'Taxes - Sales',
    categoryId: 'taxessales-md-paper-ionicons',
    iconName: 'md-paper',
    iconLibrary: 'Ionicons',
  },
  'taxesproperty-md-paper-ionicons': {
    isStandardCategory: true,
    categoryName: 'Taxes - Property',
    categoryId: 'taxesproperty-md-paper-ionicons',
    iconName: 'md-paper',
    iconLibrary: 'Ionicons',
  },
  'television-television-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Television',
    categoryId: 'television-television-materialcommunityicons',
    iconName: 'television',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'toys-pinwheel-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Toys',
    categoryId: 'toys-pinwheel-materialcommunityicons',
    iconName: 'pinwheel',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'tuition-school-materialcommunityicons': {
    isStandardCategory: true,
    categoryName: 'Tuition',
    categoryId: 'tuition-school-materialcommunityicons',
    iconName: 'school',
    iconLibrary: 'MaterialCommunityIcons',
  },
  'utilities-md-power-ionicons': {
    isStandardCategory: true,
    categoryName: 'Utilities',
    categoryId: 'utilities-md-power-ionicons',
    iconName: 'md-power',
    iconLibrary: 'Ionicons',
  },
  'vacation-map-feather': {
    isStandardCategory: true,
    categoryName: 'Vacation',
    categoryId: 'vacation-map-feather',
    iconName: 'map',
    iconLibrary: 'Feather',
  },
};
