// Using Ionicons, Feather, and MaterialCommunityIcon

export const standardCategoryList = [
  {
    categoryName: 'Investment',
    categoryId: 'investment-currency-usd-materialcommunityicon',
    iconName: 'currency-usd',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Music',
    categoryId: 'music-headphones-materialcommunityicon',
    iconName: 'headphones',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Movies',
    categoryId: 'movies-filmstrip-materialcommunityicon',
    iconName: 'filmstrip',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Events',
    categoryId: 'events-star-feather',
    iconName: 'star',
    iconLibrary: 'Feather',
  },
  {
    categoryName: 'Newspaper & Magazines',
    categoryId: 'newspapermagazines-newspaper-materialcommunityicon',
    iconName: 'newspaper',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Tuition',
    categoryId: 'tuition-school-materialcommunityicon',
    iconName: 'school',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Student Loan',
    categoryId: 'studentloan-school-materialcommunityicon',
    iconName: 'school',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'School Supplies',
    categoryId: 'schoolsupplies-school-materialcommunityicon',
    iconName: 'school',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Clothing',
    categoryId: 'clothing-watch-materialcommunityicon',
    iconName: 'watch',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Books',
    categoryId: 'books-book-open-variant-materialcommunityicon',
    iconName: 'book-open-variant',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Electronics',
    categoryId: 'electronics-cellphone-link-materialcommunityicon',
    iconName: 'cellphone-link',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Software',
    categoryId: 'software-logo-windows-ionicons',
    iconName: 'logo-windows',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Hobbies',
    categoryId: 'hobbies-happy-ionicons',
    iconName: 'happy',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Sporting Goods',
    categoryId: 'sportinggoods-basketball-materialcommunityicon',
    iconName: 'basketball',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Laundry',
    categoryId: 'laundry-washing-machine-materialcommunityicon',
    iconName: 'washing-machine',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Gym',
    categoryId: 'gym-dumbbell-materialcommunityicon',
    iconName: 'dumbbell',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Hair',
    categoryId: 'hair-cut-ionicons',
    iconName: 'cut',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Spa & Massage',
    categoryId: 'spamassage-spa-materialcommunityicon',
    iconName: 'spa',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Dentist',
    categoryId: 'dentist-medkit-ionicons',
    iconName: 'medkit',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Doctor',
    categoryId: 'doctor-medkit-ionicons',
    iconName: 'medkit',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Eye Care',
    categoryId: 'eyecare-eye-materialcommunityicon',
    iconName: 'eye',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Pharmacy',
    categoryId: 'pharmacy-pharmacy-materialcommunityicon',
    iconName: 'pharmacy',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Health Insurance',
    categoryId: 'healthinsurance-medkit-ionicons',
    iconName: 'medkit',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Sports',
    categoryId: 'sports-football-ionicons',
    iconName: 'football',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Baby Supplies',
    categoryId: 'babysupplies-baby-carriage-materialcommunityicon',
    iconName: 'baby-carriage',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Babysitter & Daycare',
    categoryId: 'babysitterdaycare-baby-carriage-materialcommunityicon',
    iconName: 'baby-carriage',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Child Support',
    categoryId: 'childsupport-baby-face-materialcommunityicon',
    iconName: 'baby-face',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Toys',
    categoryId: 'toys-pinwheel-materialcommunityicon',
    iconName: 'pinwheel',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Groceries',
    categoryId: 'groceries-cart-materialcommunityicon',
    iconName: 'cart',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Coffee Shops',
    categoryId: 'coffeeshops-coffee-materialcommunityicon',
    iconName: 'coffee',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Fast Food',
    categoryId: 'fastfood-pizza-ionicons',
    iconName: 'pizza',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Restaurants',
    categoryId: 'restaurants-silverware-fork-knife-materialcommunityicon',
    iconName: 'silverware-fork-knife',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Alcohol',
    categoryId: 'alcohol-glass-cocktail-materialcommunityicon',
    iconName: 'glass-cocktail',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Charity',
    categoryId: 'gifts-charity-materialcommunityicon',
    iconName: 'charity',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Gifts',
    categoryId: 'gifts-gift-ionicons',
    iconName: 'gift',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Television',
    categoryId: 'television-television-materialcommunityicon',
    iconName: 'television',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Home Phone',
    categoryId: 'homephone-phone-materialcommunityicon',
    iconName: 'phone',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Internet',
    categoryId: 'internet-globe-ionicons',
    iconName: 'globe',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Mobile Phone',
    categoryId: 'mobilephone-cellphone-materialcommunityicon',
    iconName: 'cellphone',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Utilities',
    categoryId: '-paper-ionicons',
    iconName: 'power',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Rent',
    categoryId: 'rent-home-city-materialcommunityicon',
    iconName: 'home-city',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Home Repairs',
    categoryId: 'homerepairs-home-materialcommunityicon',
    iconName: 'home',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Public Transportation',
    categoryId: 'publictransportation-bus-materialcommunityicon',
    iconName: 'bus',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Gas & Fuel',
    categoryId: 'gasfuel-gas-station-materialcommunityicon',
    iconName: 'gas-station',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Parking',
    categoryId: 'parking-parking-materialcommunityicon',
    iconName: 'parking',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Service & Auto Parts',
    categoryId: 'serviceautoparts-towing-materialcommunityicon',
    iconName: 'towing',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Auto Payment',
    categoryId: 'autopayment-car-materialcommunityicon',
    iconName: 'car',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Auto Insurancce',
    categoryId: 'autoinsurance-car-materialcommunityicon',
    iconName: 'car',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Air Travel',
    categoryId: 'airtravel-airplane-materialcommunityicon',
    iconName: 'airplane',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Hotel',
    categoryId: 'hotel-hotel-materialcommunityicon',
    iconName: 'hotel',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Rental Car',
    categoryId: 'rentalcar-car-materialcommunityicon',
    iconName: 'car',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Taxis & Rideshares',
    categoryId: 'taxisrideshares-taxi-materialcommunityicon',
    iconName: 'taxi',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Vacation',
    categoryId: 'vacation-map-feather',
    iconName: 'map',
    iconLibrary: 'Feather',
  },
  {
    categoryName: 'Service Fee',
    categoryId: 'servicefee-message-alert-materialcommunityicon',
    iconName: 'message-alert',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Late Fee',
    categoryId: 'latefee-messagealert-materialcommunityicon',
    iconName: 'message-alert',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'ATM Fee',
    categoryId: 'atmfee-atm-materialcommunityicon',
    iconName: 'atm',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Bank Fee',
    categoryId: 'bankfee-bank-materialcommunityicon',
    iconName: 'bank',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Office Supplies',
    categoryId: 'officesupplies-paperclip-feather',
    iconName: 'paperclip',
    iconLibrary: 'Feather',
  },
  {
    categoryName: 'Printing',
    categoryId: 'printing-printer-materialcommunityicon',
    iconName: 'printer',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Shipping',
    categoryId: 'shipping-truck-materialcommunityicon',
    iconName: 'truck',
    iconLibrary: 'MaterialCommunityIcon',
  },
  {
    categoryName: 'Legal',
    categoryId: 'legal-paper-ionicons',
    iconName: 'paper',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Taxes - Federal',
    categoryId: 'taxesfederal-paper-ionicons',
    iconName: 'paper',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Taxes - State',
    categoryId: 'taxesstate-paper-ionicons',
    iconName: 'paper',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Taxes - Local',
    categoryId: 'taxeslocal-paper-ionicons',
    iconName: 'paper',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Taxes - Sales',
    categoryId: 'taxessales-paper-ionicons',
    iconName: 'paper',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Taxes - Property',
    categoryId: 'taxesproperty-paper-ionicons',
    iconName: 'paper',
    iconLibrary: 'Ionicons',
  },
  {
    categoryName: 'Other',
    categoryId: 'other-help-circle-materialcommunityicon',
    iconName: 'help-circle',
    iconLibrary: 'MaterialCommunityIcon',
  },
];
